### ISSUE TITLE
Linking to Scratch Homepage

### ISSUE THREAD

**Issue by TheGrits** [scratchdesignstudio/quick-link#12]
Is it just me, or does it only link to the Scratch homepage?

No errors in my Chrome console. EDIT: Now giving me a 504 error on `crossorigin.me`

@technoboy10

**Comment by hyperobject** [comment]
That's an issue with crossorigin.me lag spikes. They tend to go away after
a couple hours, but I need to add some error catching in main.js.

On Mar 6, 2017 11:20, "The_Grits" <notifications@github.com> wrote:

Is it just me, or does it only link to the Scratch homepage?

No errors in my Chrome console.

@technoboy10 <https://github.com/technoboy10>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/scratchdesignstudio/quick-link/issues/12>, or mute the
thread

**Comment by TheGrits** [comment]
Looking good again.
