### ISSUE TITLE
Not working? Problem with Crossorigin.me... 

### ISSUE THREAD

**Issue by LiFaytheGoblin** [scratchdesignstudio/quick-link#9]
Hi!

For me neither the sds quick link nor the welcoming committe quick link work. 
I get the following error in the console:

https://crossorigin.me/https://scratch.mit.edu/site-api/comments/gallery/146521/?page=1. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://lifaythegoblin.github.io' is therefore not allowed access. The response had HTTP status code 522.

Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://crossorigin.me/https://scratch.mit.edu/site-api/users/curators-in/3479432/1/'.
    at getCurators (https://scratchdesignstudio.github.io/quick-link/main.js:80:16)
    at nextLink (https://scratchdesignstudio.github.io/quick-link/main.js:119:3)
    at onload (https://scratchdesignstudio.github.io/quick-link/:9:72)

@technoboy10

**Comment by TheGrits** [comment]
@LiFaytheGoblin Thanks for the report, I'll try to email @technoboy10 via the link on crossorigin.me as well, hopefully he'll have some time to fix it soon. (No pressure @technoboy10 though! Only do it when you have time, your studies are more important!)

**Comment by hyperobject** [comment]
Yep, crossorigin.me is being flaky at the moment, but I'm super busy with
exams at uni so I can't really fix it right now :(

On Dec 6, 2016 7:42 AM, "The_Grits" <notifications@github.com> wrote:

@LiFaytheGoblin <https://github.com/LiFaytheGoblin> Thanks for the report,
I'll try to email @technoboy10 <https://github.com/technoboy10> via the
link on crossorigin.me as well, hopefully he'll have some time to fix it
soon. (No pressure @technoboy10 <https://github.com/technoboy10> though!
Only do it when you have time, your studies are more important!)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/scratchdesignstudio/quick-link/issues/9#issuecomment-265166601>,
or mute the thread

**Comment by hyperobject** [comment]
Should be fixed (ish?) now, but there's other issues with the code. Gonna close this for now.
